# Generated by Django 5.2 on 2025-05-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
