# Generated by Django 5.2 on 2025-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_codequestion_audio_url_codequestion_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learncontent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='learncontent',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learncontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learncontent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='learncontent',
            unique_together={('milestone', 'order')},
        ),
    ]
