# Generated by Django 5.2 on 2025-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_learncontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='video_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='audio_url_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
